### ISSUE TITLE
I'm trying to use it at runtime but the hex string can't be found

### ISSUE THREAD

**Issue by avengah** [Kein/awsgtools#2]
Maybe something changed during a recent patch, but it doesn't work. The CheatUI still works though so I don't know what the problem is - that hex string in the readme is nowhere to be found in the process memory though.
![image](https://github.com/Kein/awsgtools/assets/285430/c491be7b-0ff7-4045-952d-a512be61c547)

**Comment by Kein** [comment]
You are searching for ASCII, where as given "string" is a sequence of bytes in HEX notation. Use "HEX" search mode

**Comment by avengah** [comment]
Oh, silly me. I thought I set it to Hex. But even so, it's still not working and I'm getting a read error. I did a hacky temporary fix by editing the template to the following, based on searching for things I knew were in the save, but I don't expect this to work every time if the addresses are dynamic.
![image](https://github.com/Kein/awsgtools/assets/285430/c4d7b2f0-2bf5-497e-a9d6-cf6ffe5fa2bc)

I'll try again and update. This was the read error I got.
![image](https://github.com/Kein/awsgtools/assets/285430/b630aeb8-c2b8-4819-8cc5-acec8c1a03ff)

**Comment by avengah** [comment]
Yeah, it still can't be found. I closed everything else and it did the search, but couldn't find it.

![image](https://github.com/Kein/awsgtools/assets/285430/56e55459-e6cf-4d95-a770-6d87c14443de)

I tried again shortly afterwards and got another read error.

If I select "Open Only Writeable Bytes" in Options, I don't get a read error but it still isn't finding it.

![image](https://github.com/Kein/awsgtools/assets/285430/31017999-ac05-47a0-a79a-503cbe4dbb66)

I was able to temporarily get it working this time by editing the template as before: I loaded my save file, searched the process for the first 15 or so bytes of the slot (slot 0 in this case) and told it to start there - in this case, setting that line to a value of 8424458 in hex, which I converted to decimal as "return AddressFileToLocal(138560600);". So the save is clearly in memory but the string I'm supposed to search for still doesn't seem to be anywhere to be found.

**Comment by Kein** [comment]
That means it has been changed after the update - nothing much I can do about it, sorry. That suggestion was just a quick dirty hack, not a proper guideline.

**Comment by avengah** [comment]
OK, no problem, thanks.

**Comment by avengah** [comment]
I may have a solution. If I load my save into 010 editor, and run Animal Well and load the slot I'm intending to run, I can pick that slot in the save file, copy the first few bytes with Ctrl-Shift-C, search for that in memory in the process to find where it starts and run this version of the template from that position, and it works perfectly. I just use GetCursorPos() as shown. The only thing is, this version of the template only works in runtime because I set the number of slots to 1, but that can be changed back to 3 if you don't mind seeing garbage data in the later slots if used during runtime.

![image](https://github.com/Kein/awsgtools/assets/285430/0752bb6c-ff88-44bd-966a-ec9de69ce078)

**Comment by avengah** [comment]
I got it working better I think. I need to test more, but if you just search for the first few bytes of the save, including the GlobalState, with this version of the last lines of the template, it seems to work.

![2024-07-03 (7)](https://github.com/Kein/awsgtools/assets/285430/77c29417-e6fd-43f6-af90-5bc1a7e0efff)
